version: '3.4'

services:
  multiplayerpiano:
    image: multiplayerpiano
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MPP_HTTP_PORT: ${MPP_HTTP_PORT}
      MPP_HTTPS_PORT: ${MPP_HTTPS_PORT}
      MPP_DEBUG: 'true'
      MPP_MONGO_URI: mongodb://mongo:${MPP_MONGO_PORT}/multiplayerpiano
      MPP_SALT: ${MPP_SALT}
    ports:
      - ${MPP_HTTP_PORT}:${MPP_HTTP_PORT}
      - ${MPP_HTTPS_PORT}:${MPP_HTTPS_PORT}
  mongo:
    image: 'mongo'
    container_name: multiplayerpiano-mongodb
    # command: ["--replSet", "replica"]
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mppdb:/data/db
    ports:
      - ${MPP_MONGO_PORT}:27017
    restart: unless-stopped

volumes:
  mppdb:
    
